Include resource title in required attr exception
Based on helping with this issue:
http://stackoverflow.com/questions/40118794/dynamically-create-n-number-of-ec2-instances-with-troposphere/40122167?noredirect=1#comment67537659_40122167

Now, if a resource is missing a required attribute, and that resource
has a title, we'll include it in the exception.

ValueError: Resource ImageId required in type AWS::EC2::Instance

vs

ValueError: Resource ImageId required in type AWS::EC2::Instance (title: MyInstance)